# Generated by Django 4.0.3 on 2022-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_password_passwords_pass_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='pass_word',
        ),
        migrations.AddField(
            model_name='passwords',
            name='key',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
