# Generated by Django 4.0.3 on 2022-04-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
