# Generated by Django 4.0.3 on 2022-04-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_id',
        ),
    ]
