# Generated by Django 4.0.3 on 2022-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_newuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='u_id',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
    ]
