# Generated by Django 4.0.3 on 2022-04-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_newuser_status_newuser_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwords',
            name='u_id',
            field=models.CharField(blank=True, default='0', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='u_id',
            field=models.CharField(blank=True, default='0', max_length=100, unique=True),
        ),
    ]
