# Generated by Django 4.0.3 on 2022-04-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_passwords_u_id_store_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='u_id',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='u_id',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
