# Generated by Django 4.0.3 on 2022-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_passwords_u_id_alter_store_u_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='otp_t',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
