# Generated by Django 4.0.3 on 2022-04-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_store_otp_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Phone',
        ),
    ]
